os: osx
osx_image: xcode10.2
compiler:
  - clang
  - gcc
  - python

addons:
  homebrew:
    packages:
    - cmake
    - conan
    - nasm
    - llvm@6

before_cache:
  - brew cleanup

cache:
  - directories:
    - $HOME/Library/Caches/Homebrew

jobs:
  include:
    - script:
        - echo "BUILDING KERNEL"
        - conan create . includeos/latest -pr clang-6.0-macos-x86_64
        - echo "BUILDING LiveUpdate"
        - conan create lib/LiveUpdate includeos/latest -pr clang-6.0-macos-x86_64
        - conan install hello_world -pr clang-6.0-macos-x86_64
        - source activate.sh
        - cmake hello_world
        - cmake --build .
        - gtimeout 7 boot hello > hello_log.txt || true
        - |
          if grep -F "Running [ Hello world - OS included ]" hello_log.txt
          then
            echo "Hello World -  Success! :)"
          else
            echo "Failed :("
          fi
      name: "clang-6.0-x86_64"

before_install:
  - git fetch --tags https://github.com/includeos/IncludeOS.git

install:
  - conan config install https://github.com/includeos/conan_config.git
  - conan --version
  - clang --version
  - pip install future

before_script:
  - git clone https://github.com/includeos/hello_world

after_script:
  - source deactivate.sh
