os: osx
osx_image: xcode10.2
compiler:
  - clang
  - gcc

addons:
  homebrew:
    packages:
    - cmake
    - conan
    - nasm
    - llvm@6

before_cache:
  - brew cleanup

cache:
  - directories:
    - $HOME/Library/Caches/Homebrew

jobs:
  include:
    - script:
        - echo "BUILDING KERNEL"
        - conan create . includeos/latest -pr clang-6.0-macos-x86_64
        - echo "BUILDING LiveUpdate"
        - conan create lib/LiveUpdate includeos/latest -pr clang-6.0-macos-x86_64
        - echo "BUILD and BOOT Hello World!"
        - git clone https://github.com/includeos/hello_world
        - conan install hello_world -pr clang-6.0-macos-x86_64
        - source activate.sh
        - cmake -DFOR_PRODUCTION=OFF hello_world
        - cmake --build .
        - boot hello
        - |
          if grep -F "Running [ Hello world - OS included ]" hello.log
          then
            echo "Hello World -  Success! :)"
          else
            exit 1
          fi
      name: "clang-6.0-x86_64"

before_install:
  - git pull https://github.com/includeos/IncludeOS.git master
  - git fetch --tags https://github.com/includeos/IncludeOS.git

install:
  - conan config install https://github.com/includeos/conan_config.git
  - conan --version
  - clang --version
  - pip3 install future
  - pip3 install --upgrade psutil
  - pip3 install --upgrade jsonschema
