os: osx
osx_image: xcode10.2
compiler:
  - clang
  - gcc

addons:
  homebrew:
    packages:
    - cmake
    - conan
    - nasm
    - llvm

matrix:
  include:
    - stage: IncludeOS-x86_64
      script:
        - echo "x86_64"
        - conan create . includeos/latest -pr clang-6.0-macos-x86_64

    - stage: IncludeOS-nano
      script:
        - echo "IncludeOS nano"
        - conan create . includeos/latest -pr clang-6.0-macos-x86_64 -o platform=nano

    - stage: IncludeOS-x86
      script:
        - echo "IncludeOS chainloader x86"
        - conan create src/chainload includeos/latest -pr clang-6.0-macos-x86_64

install:
  - conan config install https://github.com/includeos/conan_config.git
  - conan --version
  - brew update
  - clang --version
