os: osx
osx_image: xcode10.2
compiler:
  - clang
  - gcc

env:
  - CC=clang-5.0
  - CXX=clang++-5.0

addons:
  homebrew:
    packages:
    - cmake
    - conan
    - nasm

matrix:
  include:
    - stage: IncludeOS-x86_64
      script:
        - echo "x86_64"
        - conan create . includeos/latest -pr clang-6.0-linux-x86_64

    - stage: IncludeOS-nano
      script:
        - echo "IncludeOS nano"
        - env: COMPILER='clang++'
        - conan create . includeos/latest -pr clang-6.0-linux-x86 -o platform=nano

    - stage: IncludeOS-x86
      script:
        - echo "IncludeOS chainloader x86"
        - conan create src/chainload includeos/latest -pr clang-6.0-linux-x86

before_cache:
  - brew cleanup

cache:
  - directories:
    - $HOME/Library/Caches/Homebrew

install:
  - conan config install https://github.com/includeos/conan_config.git
  - conan --version
  - brew install llvm
  - brew update
  - clang --version
  - gcc --version

after_success:
  - echo "Success!"
