os: osx
osx_image: xcode10.2
compiler:
  - clang
  - gcc

env: COMPILER='clang++'

addons:
  homebrew:
    packages:
    - cmake
    - conan

matrix:
  include:
    - stage: IncludeOS-nano
      script:
        - echo "IncludeOS nano"
        - conan create . includeos/latest -pr clang-6.0-linux-x86 -o platform=nano

    - stage: IncludeOS-x86
      script:
        - echo "IncludeOS chainloader x86"
        - conan create src/chainload includeos/latest -pr clang-6.0-linux-x86

    - stage: IncludeOS-x86_64
      script:
        - echo "x86_64"
        - conan create . includeos/latest -pr clang-6.0-linux-x86_64

install:
  - conan config install https://github.com/includeos/conan_config.git
  - conan --version

after_success:
  - echo "Success!"
