os: osx
osx_image: xcode10.2
compiler:
  - clang
  - gcc

addons:
  homebrew:
    packages:
    - cmake
    - conan
    - nasm
    - llvm@6

jobs:
  include:
    - stage: kernel
      script: conan create . includeos/latest -pr clang-6.0-macos-x86_64
      name: "Building Kernel x86_64"
    - stage: liveupdate
      script: conan create lib/LiveUpdate includeos/latest -pr clang-6.0-macos-x86_64
      name: "LiveUpdate on Kernel x86_64"

before_install:
  - export CC=/usr/local/opt/llvm\@6/bin/clang
  - export CXX=/usr/local/opt/llvm\@6/bin/clang++
  - git fetch --tags https://github.com/includeos/IncludeOS.git

install:
  - conan config install https://github.com/includeos/conan_config.git
  - conan --version
  - clang --version
