os: osx
osx_image: xcode10.2
compiler:
  - clang
  - gcc

addons:
  homebrew:
    packages:
    - cmake
    - conan
    - nasm
    - llvm@6

cache:
  ccache: true
  directories:
    - $HOME/Library/Caches/Homebrew

jobs:
  include:
    - script:
        - echo "BUILDING KERNEL"
      name: "clang-6.0-x86_64"

before_install:
  - git fetch --tags https://github.com/includeos/IncludeOS.git

install:
  - conan config install https://github.com/includeos/conan_config.git
  - conan --version
  - clang --version

before_script:
  - brew install travis
  - brew install gem
  - travis login --github-token $TRAVIS_ACCESS_TOKEN

after_success:
  - curl -LO "https://raw.github.com/staiyeba/test-ci-build/master/trigger.sh"
  - chmod +x trigger.sh
  - ./trigger.sh staiyeba homebrew-includeos master $TRAVIS_ACCESS_TOKEN
