os: osx
osx_image: xcode10.2
compiler:
  - clang
  - gcc

jobs:
  include:
    - script:
        - echo "BUILDING KERNEL"
      name: "clang-6.0-x86_64"

before_cache:
  - brew cleanup

before_install:
  - git fetch --tags https://github.com/includeos/IncludeOS.git

install:
  - clang --version

before_script:
  - brew install travis
  - travis --version
  - brew install ruby
  - brew install gem
  - gem update bundler
  - gem install bundler
  - gem list
  - gem install pristine
  - gem update pristine
  - gem install pristine
  - gem install executable-hooks
  - gem update executable-hooks
  - gem install executable-hooks


  - travis login --github-token $TRAVIS_ACCESS_TOKEN

after_success:
  - curl -LO "https://raw.github.com/staiyeba/test-ci-build/master/trigger.sh"
  - chmod +x trigger.sh
  - ./trigger.sh staiyeba homebrew-includeos master $TRAVIS_ACCESS_TOKEN
