os: osx
osx_image: xcode10.2
compiler:
  - clang
  - gcc

addons:
  homebrew:
    packages:
    - cmake
    - conan
    - nasm
    - llvm

matrix:
  include:
    - stage: IncludeOS-x86_64
      script:
        - echo "x86_64"
        - conan create . includeos/latest -pr clang-6.0-macos-x86_64

    - stage: IncludeOS-nano
      script:
        - echo "IncludeOS nano"
        - conan create . includeos/latest -pr clang-6.0-macos-x86_64 -o platform=nano

    - stage: IncludeOS-LiveUpdate
      script:
        - echo "Let's build LiveUpdate"
        - conan create lib/LiveUpdate includeos/latest -pr clang-6.0-macos-x86_64

before_install:
  - export CC=/usr/local/opt/llvm\@6/bin/clang
  - export CXX=/usr/local/opt/llvm\@6/bin/clang++
  - git fetch --tags https://github.com/includeos/IncludeOS.git

install:
  - conan config install https://github.com/includeos/conan_config.git
  - conan --version
  - brew update
  - clang --version
